apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
spec:
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer